server:
  port: 1110

spring:
  application:
    name: shorter
  liquibase:
    change-log: classpath:db/master.xml


  datasource:
#    url: jdbc:postgresql://localhost:5432/shorter?currentSchema=link&useSSL=false
#    username: root
#    password: root
    url: jdbc:postgresql://ep-sparkling-term-a5479y8z.us-east-2.aws.neon.tech/shorter?currentSchema=link&useSSL=false
    username: shorter_owner
    password: WuN1ZL0rKOhx
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect


links:
    length: 6
    iteration: 2000
    shortHost: https://localhost/
